// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddtabletblFileInfoData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddtabletblFileInfoData));
        
        string IMigrationMetadata.Id
        {
            get { return "201810131402106_Add table tblFileInfoData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
